package:
  name: instant
  version: "1.5.0+"

source:
  git_url: https://bitbucket.org/fenics-project/instant.git

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - cmake
    - swig

test:
  imports:
    - instant

  commands:
    - instant-clean
    - instant-showcache

  requires:
    - nose

about:
  home: http://www.fenicsproject.org
  license: BSD License or The GNU Lesser General Public License, version 3.0
  summary: 'Instant Inlining of C/C++ in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
